sudo: false
language: python
python:
  - 3.7.2

install: "make"
# command to run tests
script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      script:
        - |
          if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
        - make ci
    - stage: coverage
      python: 3.6
      script: codecov
